### ISSUE TITLE
Support for uploading files with strictly defined filenames

### ISSUE THREAD

**Issue by emschenn** [lokalise/lokalise-push-action#5]
Hi,

Our team is exploring the use of this action to replace our existing Lokalise app trigger for pulling translations from GitHub. We believe this approach offers greater flexibility and integration options~

However, I noticed that the action seems to restrict uploaded files to formats like:

- `{path}/{lang}.pot`
- `{path}/{lang}/**.pot`

I’m wondering if there’s a way to upload a strictly defined filename that isn’t constrained by `lang`. For instance, in our case:
`{path}/template.pot`

Thank you! 🙏🏼

**Comment by bodrovis** [comment]
Thank you for reporting this! Yep, I see the issue. This is a pretty raw solution and initially we developed it with certain assumptions. I'll look into this functionality

**Comment by bodrovis** [comment]
https://github.com/lokalise/lokalise-push-action/pull/6

**Comment by bodrovis** [comment]
This should be implemented in v3.1.1. For example:

```yaml
      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@v3.1.1
        id: lokalise-push
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 5868381966b39e5053ff15.63486389
          base_lang: en
          translations_path: |
            locales
            i18n
          file_format: json
          name_pattern: "en/**/custom_*.json"
```

Should search for `locales/en/**/custom_*.json` and `i18n/en/**/custom_*.json`.

When set to `name_pattern: "custom_*.json"`, should search for `locales/custom_*.json` and `i18n/custom_*.json`.

Please let me know how it works and if it covers your needs
